version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: aharsetu_db
    restart: always
    environment:
      POSTGRES_USER: shubh
      POSTGRES_PASSWORD: 6906
      POSTGRES_DB: aharsetu
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: aharsetu_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://shubh:6906@db:5432/aharsetu
      - SECRET_KEY=super_secret_session_token_key_for_aharsetu_erp_2026
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - BACKEND_CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      - db

volumes:
  postgres_data:
