// ── AharSetu Demo Users & Seed Data ──────────────────────────────────────────

export const SEED_USERS = [
  // ── Administrator ─────────────────────────────────────────────────────────
  {
    id: 'u-admin',
    name: 'Vin Sir',
    email: 'admin@aharsetu.edu.in',
    password: 'Admin@123',
    role: 'admin',
    department: null,
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 90 * 864e5).toISOString(),
  },

  // ── DCR ───────────────────────────────────────────────────────────────────
  {
    id: 'u-dcr',
    name: 'Neha Mam',
    email: 'dcr@aharsetu.edu.in',
    password: 'DCR@123',
    role: 'dcr',
    department: null,
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 85 * 864e5).toISOString(),
  },

  // ── Coordinators ──────────────────────────────────────────────────────────
  {
    id: 'u-coord-diploma',
    name: 'Nandini Mam',
    email: 'coord.diploma@aharsetu.edu.in',
    password: 'Coord@123',
    role: 'coordinator',
    department: 'diploma',
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 80 * 864e5).toISOString(),
  },
  {
    id: 'u-coord-degree',
    name: 'Piyush Sir',
    email: 'coord.degree@aharsetu.edu.in',
    password: 'Coord@123',
    role: 'coordinator',
    department: 'degree',
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 80 * 864e5).toISOString(),
  },
  {
    id: 'u-coord-pharmacy',
    name: 'Anita Desai',
    email: 'coord.pharmacy@aharsetu.edu.in',
    password: 'Coord@123',
    role: 'coordinator',
    department: 'pharmacy',
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 80 * 864e5).toISOString(),
  },
  {
    id: 'u-coord-physio',
    name: 'Sanjay Shah',
    email: 'coord.physio@aharsetu.edu.in',
    password: 'Coord@123',
    role: 'coordinator',
    department: 'physiotherapy',
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'gu',
    active: true,
    createdAt: new Date(Date.now() - 80 * 864e5).toISOString(),
  },
  {
    id: 'u-coord-nursing',
    name: 'Kavita Patel',
    email: 'coord.nursing@aharsetu.edu.in',
    password: 'Coord@123',
    role: 'coordinator',
    department: 'nursing',
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'gu',
    active: true,
    createdAt: new Date(Date.now() - 80 * 864e5).toISOString(),
  },
  {
    id: 'u-coord-bsc',
    name: 'Amit Verma',
    email: 'coord.bsc@aharsetu.edu.in',
    password: 'Coord@123',
    role: 'coordinator',
    department: 'bsc',
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 80 * 864e5).toISOString(),
  },

  // ── Principals ────────────────────────────────────────────────────────────
  {
    id: 'u-principal-dd',
    name: 'Pranav Sir',
    email: 'principal.dd@aharsetu.edu.in',
    password: 'Principal@123',
    role: 'principal',
    department: null,
    principalDepts: ['diploma', 'degree'],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 85 * 864e5).toISOString(),
  },
  {
    id: 'u-principal-pharma',
    name: 'Sachin Sir',
    email: 'principal.pharma@aharsetu.edu.in',
    password: 'Principal@123',
    role: 'principal',
    department: null,
    principalDepts: ['pharmacy'],
    vendorId: null,
    preferredLanguage: 'hi',
    active: true,
    createdAt: new Date(Date.now() - 85 * 864e5).toISOString(),
  },
  {
    id: 'u-principal-physio',
    name: 'Dr. J. P. Vyas',
    email: 'principal.physio@aharsetu.edu.in',
    password: 'Principal@123',
    role: 'principal',
    department: null,
    principalDepts: ['physiotherapy'],
    vendorId: null,
    preferredLanguage: 'gu',
    active: true,
    createdAt: new Date(Date.now() - 85 * 864e5).toISOString(),
  },
  {
    id: 'u-principal-nursing',
    name: 'Dr. Sarita Rao',
    email: 'principal.nursing@aharsetu.edu.in',
    password: 'Principal@123',
    role: 'principal',
    department: null,
    principalDepts: ['nursing'],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 85 * 864e5).toISOString(),
  },
  {
    id: 'u-principal-bsc',
    name: 'Dr. B. K. Bansal',
    email: 'principal.bsc@aharsetu.edu.in',
    password: 'Principal@123',
    role: 'principal',
    department: null,
    principalDepts: ['bsc'],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 85 * 864e5).toISOString(),
  },

  // ── Vendors ───────────────────────────────────────────────────────────────
  {
    id: 'u-vendor1',
    name: 'Gadhvi Bhai',
    email: 'vendor1@aharsetu.edu.in',
    password: 'Vendor@123',
    role: 'vendor',
    department: null,
    principalDepts: [],
    vendorId: 'v1',
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 75 * 864e5).toISOString(),
  },
  {
    id: 'u-vendor2',
    name: 'Mitesh Bhai',
    email: 'vendor2@aharsetu.edu.in',
    password: 'Vendor@123',
    role: 'vendor',
    department: null,
    principalDepts: [],
    vendorId: 'v2',
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 75 * 864e5).toISOString(),
  },
  {
    id: 'u-vendor3',
    name: 'Bhargav Bhai',
    email: 'vendor3@aharsetu.edu.in',
    password: 'Vendor@123',
    role: 'vendor',
    department: null,
    principalDepts: [],
    vendorId: 'v3',
    preferredLanguage: 'hi',
    active: true,
    createdAt: new Date(Date.now() - 75 * 864e5).toISOString(),
  },
  {
    id: 'u-vendor4',
    name: 'Quick Snacks Manager',
    email: 'vendor4@aharsetu.edu.in',
    password: 'Vendor@123',
    role: 'vendor',
    department: null,
    principalDepts: [],
    vendorId: 'v4',
    preferredLanguage: 'gu',
    active: true,
    createdAt: new Date(Date.now() - 75 * 864e5).toISOString(),
  },
];

export const SEED_VENDORS = [
  {
    id: 'v1',
    name: 'Sharma Canteen',
    ownerName: 'Gadhvi Bhai',
    email: 'vendor1@aharsetu.edu.in',
    phone: '+91 9911223344',
    status: 'open',
    revenue: 0,
  },
  {
    id: 'v2',
    name: 'Fresh Bites',
    ownerName: 'Mitesh Bhai',
    email: 'vendor2@aharsetu.edu.in',
    phone: '+91 9922334455',
    status: 'open',
    revenue: 0,
  },
  {
    id: 'v3',
    name: 'Hot Meals',
    ownerName: 'Bhargav Bhai',
    email: 'vendor3@aharsetu.edu.in',
    phone: '+91 9933445566',
    status: 'open',
    revenue: 0,
  },
  {
    id: 'v4',
    name: 'Quick Snacks',
    ownerName: 'P. Mehta',
    email: 'vendor4@aharsetu.edu.in',
    phone: '+91 9944556677',
    status: 'open',
    revenue: 0,
  },
];
