// ── AharSetu Demo Users & Seed Data ──────────────────────────────────────────

export const SEED_USERS = [
  // ── Administrator ─────────────────────────────────────────────────────────
  {
    id: 'u-admin',
    name: 'Rajesh Gupta',
    email: 'admin@aharsetu.edu.in',
    password: 'Admin@123',
    role: 'admin',
    department: null,
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 90 * 864e5).toISOString(),
  },

  // ── DCR ───────────────────────────────────────────────────────────────────
  {
    id: 'u-dcr',
    name: 'S. Patil',
    email: 'dcr@aharsetu.edu.in',
    password: 'DCR@123',
    role: 'dcr',
    department: null,
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 85 * 864e5).toISOString(),
  },

  // ── Coordinators ──────────────────────────────────────────────────────────
  {
    id: 'u-coord-diploma',
    name: 'Priya Sharma',
    email: 'coord.diploma@aharsetu.edu.in',
    password: 'Coord@123',
    role: 'coordinator',
    department: 'diploma',
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 80 * 864e5).toISOString(),
  },
  {
    id: 'u-coord-degree',
    name: 'Ravi Kumar',
    email: 'coord.degree@aharsetu.edu.in',
    password: 'Coord@123',
    role: 'coordinator',
    department: 'degree',
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 80 * 864e5).toISOString(),
  },
  {
    id: 'u-coord-pharmacy',
    name: 'Anita Desai',
    email: 'coord.pharmacy@aharsetu.edu.in',
    password: 'Coord@123',
    role: 'coordinator',
    department: 'pharmacy',
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 80 * 864e5).toISOString(),
  },
  {
    id: 'u-coord-physio',
    name: 'Meera Joshi',
    email: 'coord.physio@aharsetu.edu.in',
    password: 'Coord@123',
    role: 'coordinator',
    department: 'physiotherapy',
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 80 * 864e5).toISOString(),
  },
  {
    id: 'u-coord-nursing',
    name: 'Kavita Patel',
    email: 'coord.nursing@aharsetu.edu.in',
    password: 'Coord@123',
    role: 'coordinator',
    department: 'nursing',
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'gu',
    active: true,
    createdAt: new Date(Date.now() - 80 * 864e5).toISOString(),
  },
  {
    id: 'u-coord-bsc',
    name: 'Suresh Mehta',
    email: 'coord.bsc@aharsetu.edu.in',
    password: 'Coord@123',
    role: 'coordinator',
    department: 'bsc',
    principalDepts: [],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 80 * 864e5).toISOString(),
  },

  // ── Principals ────────────────────────────────────────────────────────────
  {
    id: 'u-principal-dd',
    name: 'Dr. Arvind Mehta',
    email: 'principal.dd@aharsetu.edu.in',
    password: 'Principal@123',
    role: 'principal',
    department: null,
    principalDepts: ['diploma', 'degree'],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 85 * 864e5).toISOString(),
  },
  {
    id: 'u-principal-pharma',
    name: 'Dr. Rekha Sharma',
    email: 'principal.pharma@aharsetu.edu.in',
    password: 'Principal@123',
    role: 'principal',
    department: null,
    principalDepts: ['pharmacy'],
    vendorId: null,
    preferredLanguage: 'hi',
    active: true,
    createdAt: new Date(Date.now() - 85 * 864e5).toISOString(),
  },
  {
    id: 'u-principal-physio',
    name: 'Dr. Sunil Kapoor',
    email: 'principal.physio@aharsetu.edu.in',
    password: 'Principal@123',
    role: 'principal',
    department: null,
    principalDepts: ['physiotherapy'],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 85 * 864e5).toISOString(),
  },
  {
    id: 'u-principal-nursing',
    name: 'Dr. Sarita Rao',
    email: 'principal.nursing@aharsetu.edu.in',
    password: 'Principal@123',
    role: 'principal',
    department: null,
    principalDepts: ['nursing'],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 85 * 864e5).toISOString(),
  },
  {
    id: 'u-principal-bsc',
    name: 'Dr. Vikram Singh',
    email: 'principal.bsc@aharsetu.edu.in',
    password: 'Principal@123',
    role: 'principal',
    department: null,
    principalDepts: ['bsc'],
    vendorId: null,
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 85 * 864e5).toISOString(),
  },

  // ── Vendors ───────────────────────────────────────────────────────────────
  {
    id: 'u-vendor1',
    name: 'M. Khan',
    email: 'vendor1@aharsetu.edu.in',
    password: 'Vendor@123',
    role: 'vendor',
    department: null,
    principalDepts: [],
    vendorId: 'v1',
    preferredLanguage: 'gu',
    active: true,
    createdAt: new Date(Date.now() - 75 * 864e5).toISOString(),
  },
  {
    id: 'u-vendor2',
    name: 'R. Patel',
    email: 'vendor2@aharsetu.edu.in',
    password: 'Vendor@123',
    role: 'vendor',
    department: null,
    principalDepts: [],
    vendorId: 'v2',
    preferredLanguage: 'gu',
    active: true,
    createdAt: new Date(Date.now() - 75 * 864e5).toISOString(),
  },
  {
    id: 'u-vendor3',
    name: 'S. Shah',
    email: 'vendor3@aharsetu.edu.in',
    password: 'Vendor@123',
    role: 'vendor',
    department: null,
    principalDepts: [],
    vendorId: 'v3',
    preferredLanguage: 'hi',
    active: true,
    createdAt: new Date(Date.now() - 75 * 864e5).toISOString(),
  },
  {
    id: 'u-vendor4',
    name: 'D. Verma',
    email: 'vendor4@aharsetu.edu.in',
    password: 'Vendor@123',
    role: 'vendor',
    department: null,
    principalDepts: [],
    vendorId: 'v4',
    preferredLanguage: 'en',
    active: true,
    createdAt: new Date(Date.now() - 75 * 864e5).toISOString(),
  },
];

export const SEED_VENDORS = [
  {
    id: 'v1',
    name: 'Sharma Canteen',
    ownerName: 'M. Khan',
    email: 'vendor1@aharsetu.edu.in',
    phone: '+91 98765 43210',
    status: 'open',
    revenue: 1300,
    menu: [
      { id: 'v1m1', vendorId: 'v1', vendorName: 'Sharma Canteen', name: 'Tea', price: 10, unit: 'per cup', available: true },
      { id: 'v1m2', vendorId: 'v1', vendorName: 'Sharma Canteen', name: 'Coffee', price: 15, unit: 'per cup', available: true },
      { id: 'v1m3', vendorId: 'v1', vendorName: 'Sharma Canteen', name: 'Biscuits', price: 20, unit: 'per pack', available: true },
      { id: 'v1m4', vendorId: 'v1', vendorName: 'Sharma Canteen', name: 'Water', price: 5, unit: 'per bottle', available: true },
    ],
  },
  {
    id: 'v2',
    name: 'Fresh Bites',
    ownerName: 'R. Patel',
    email: 'vendor2@aharsetu.edu.in',
    phone: '+91 97654 32109',
    status: 'open',
    revenue: 960,
    menu: [
      { id: 'v2m1', vendorId: 'v2', vendorName: 'Fresh Bites', name: 'Lunch (Veg)', price: 80, unit: 'per plate', available: true },
      { id: 'v2m2', vendorId: 'v2', vendorName: 'Fresh Bites', name: 'Breakfast', price: 50, unit: 'per plate', available: true },
      { id: 'v2m3', vendorId: 'v2', vendorName: 'Fresh Bites', name: 'Cold Drinks', price: 25, unit: 'per bottle', available: false },
      { id: 'v2m4', vendorId: 'v2', vendorName: 'Fresh Bites', name: 'Juice', price: 30, unit: 'per glass', available: true },
    ],
  },
  {
    id: 'v3',
    name: 'Hot Meals',
    ownerName: 'S. Shah',
    email: 'vendor3@aharsetu.edu.in',
    phone: '+91 96543 21098',
    status: 'open',
    revenue: 0,
    menu: [
      { id: 'v3m1', vendorId: 'v3', vendorName: 'Hot Meals', name: 'Snacks', price: 30, unit: 'per plate', available: true },
      { id: 'v3m2', vendorId: 'v3', vendorName: 'Hot Meals', name: 'Lunch (Non-Veg)', price: 100, unit: 'per plate', available: true },
      { id: 'v3m3', vendorId: 'v3', vendorName: 'Hot Meals', name: 'Samosa', price: 10, unit: 'per piece', available: true },
    ],
  },
  {
    id: 'v4',
    name: 'Quick Snacks',
    ownerName: 'D. Verma',
    email: 'vendor4@aharsetu.edu.in',
    phone: '+91 95432 10987',
    status: 'closed',
    revenue: 0,
    menu: [
      { id: 'v4m1', vendorId: 'v4', vendorName: 'Quick Snacks', name: 'Samosa', price: 15, unit: 'per piece', available: true },
      { id: 'v4m2', vendorId: 'v4', vendorName: 'Quick Snacks', name: 'Fruit Juice', price: 35, unit: 'per glass', available: true },
    ],
  },
];
